# Generated by Django 4.2 on 2023-04-15 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="order",
        ),
        migrations.RemoveField(
            model_name="item",
            name="product",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shop",
        ),
        migrations.AddField(
            model_name="item",
            name="product_reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.shopproduct",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="unit",
            field=models.CharField(blank=True, default="", max_length=42, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="size_unit",
            field=models.CharField(default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="item",
            name="devise",
            field=models.CharField(blank=True, default="", max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="quantity",
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name="ShopOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(default="", max_length=120)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.order",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.shop",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="shop_order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.shoporder",
            ),
        ),
    ]
